server:
  port: 8000
spring:
  application:
    name: spring-cloud-eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    # 是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
    # 是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#    serviceUrl:http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone:
