server:
  port: 8003
spring:
  application:
    name: spring-cloud-config-client
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host:
    port:
    username:
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/